export default {
	profile_ru: 'личный кабинет',
	profile_uk: 'משרד אישי',
	cart_ru: 'корзина',
	cart_uk: 'סַל',
	reviews_ru: 'отзывы',
	reviews_uk: 'ביקורות',
	orders_ru: 'заказы',
	orders_uk: 'להזמין',
	checkout_ru: 'оформление заказа',
	checkout_uk: 'מזמין',
	delivery_payment_ru: 'доставка и оплата',
	delivery_payment_uk: 'משלוח ותשלום',
	contacts_ru: 'контакты',
	contacts_uk: 'אנשי קשר',
	about_us_ru: 'о магазине',
	about_us_uk: 'על החנות',
	privacy_policy_ru: 'политика конфиденциальности',
	privacy_policy_uk: 'מדיניות פרטיות',
	new_products_ru: 'новинки',
	new_products_uk: 'פריטים חדשים',
};